# Site settings
title: Kyle Coberly
email: kyle.coberly@gmail.com
name: Kyle Coberly
description: Educator, business dork, software developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kylecoberly.com" # the base hostname & protocol for your site
twitter_username: kylecoberly
github_username: kylecoberly
year: 2017
social-links:
  - url: "http://www.github.com/kylecoberly"
    class: "github-logo"
  - url: "http://www.twitter.com/kylecoberly"
    class: "twitter-logo"
  - url: "http://www.linkedin.com/in/kylecoberly"
    class: "linkedin-logo"
  - url: "/feed.xml"
    class: "rss-logo"
collections:
  presentations:
    output: true

# Build settings
destination: _site
timezone: America/Denver
markdown: kramdown
encoding: UTF-8
kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: false
sass:
  sass_dir: _sass
  style: compressed
